### ISSUE TITLE
Exception killing server

### ISSUE THREAD

**Issue by jedireza** [spacekit/spacekit#18]
I've noticed a couple times that after the server has been running idle for a while an exception is thrown and kills the server. This is what shows on the console:

``` bash
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:870:11)
    at TCP.onread (net.js:544:26)
```

**Comment by mcav** [comment]
We're probably not handling an 'error' event that's getting fired from one of the sockets. StackOverflow-fu points to [this answer](http://stackoverflow.com/questions/17245881/node-js-econnreset) recommending that we could also use [longjohn](https://github.com/mattinsler/longjohn) to make the stack trace point to the misbehaving socket.

**Comment by jedireza** [comment]
I've added `error` event handlers in 12975f5. Let's see if this helps with that specific error.

**Comment by jedireza** [comment]
I noticed the server crashed again, but I didn't see the console output. I just started it again and piped the output to a file called `run.log` (`... > run.log 2>&1`).

**Comment by jedireza** [comment]
Checked the log today and saw this in the log file:

```
tls proxy socket error { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
```

**Comment by jedireza** [comment]
During #30 I found we weren't listening to `error` events of the proxy servers. Service restarted with latest master. Let's see how long it can stay up now.

**Comment by jedireza** [comment]
I'll call this issue resolved for now. Future issues should be created over here: https://github.com/spacekit/spacekit-service/issues
