### ISSUE TITLE
AWS variables via environement instead of default fs location

### ISSUE THREAD

**Issue by jedireza** [spacekit/spacekit#2]

**Comment by jedireza** [comment]
This can be closed right @mcav?

**Comment by mcav** [comment]
Not unless we just don't want to do it. The [existing code is here](https://github.com/spacekit/spacekit/blob/master/server/dynamic-dns.js#L6).

**Comment by jedireza** [comment]
Ah. Thanks for pointing that out.

**Comment by jedireza** [comment]
Resolved in https://github.com/spacekit/spacekit-service/pull/1
