### ISSUE TITLE
Should we split the service and relay packages?

### ISSUE THREAD

**Issue by jedireza** [spacekit/spacekit#31]
For client only use the service is heavy with a lot of deps to install.

**Comment by jedireza** [comment]
I was just installing the relay on a RPi:

``` bash
$ npm install -g spacekit
```

which failed. I had to install build tools (in this case `apt-get install libpq-dev`) in order to complete the installation. BTW: This is because we're using the native bindings of the `pg` module. We could use the 100% js version and not have that issue probably, but I don't think that's a good long term solution.

I'd really like the `spacekit` module to install as quick as possible.

**Comment by mcav** [comment]
Sounds reasonable to me.

**Comment by jedireza** [comment]
Split out the [`spacekit-service`](https://github.com/spacekit/spacekit-service) in 3a22f0c and published to npm.
