### ISSUE TITLE
Document JSON Format

### ISSUE THREAD

**Issue by mysterycommand** [spacekit/spacekit#34]
The README covers the command line interface and options, but doesn't say what those keys should look like in a `spacekit.json` file. I'm guessing:

```
{
  "apiKey": "<whatever api key>",
  "relay": "<whatever relay name>",
  "username": "<whatever username>"
}
```

… but I would like not to guess. Am I missing anything?

**Comment by jedireza** [comment]
Thanks for opening an issue. We do need to cover this in the docs.

**Comment by jedireza** [comment]
https://github.com/spacekit/spacekit#config-file
